# ML in Finance Group Project
## Group 4: Barbara Capl, Mathias LÃ¼thi, Pamela Matias, Stefanie Rentsch

In [1]:
import pandas as pd
import numpy as np

# Load in data from the Wharton Database
df = pd.read_csv('Data/WhartonData.csv', sep=',', header=0)

df = df.drop(['SPREAD', 'HSICIG', 'DIVAMT'], 1)
df = df.drop(df.index[3364])
df.columns.values[0] = 'permno'

print(df.isnull().sum())

df['date'] = df.date.str[3:]

display(df.head())

permno    0
date      0
SICCD     0
TICKER    0
COMNAM    0
BIDLO     0
ASKHI     0
PRC       0
BID       0
ASK       0
vwretd    0
vwretx    0
dtype: int64

,permno,date,SICCD,TICKER,COMNAM,BIDLO,ASKHI,PRC,BID,ASK,vwretd,vwretx
0,10107,01/2006,7370.0,MSFT,MICROSOFT CORP,26.28,28.15,28.15,28.15,28.13,0.040044,0.038938
1,10107,02/2006,7370.0,MSFT,MICROSOFT CORP,26.39,28.04,26.87,26.87,26.88,-0.001637,-0.003552
2,10107,03/2006,7370.0,MSFT,MICROSOFT CORP,26.85,27.89,27.21,27.24,27.24,0.019053,0.017585
3,10107,04/2006,7370.0,MSFT,MICROSOFT CORP,24.15,27.74,24.15,24.16,24.16,0.012965,0.011494
4,10107,05/2006,7370.0,MSFT,MICROSOFT CORP,22.56,24.29,22.65,22.70,22.70,-0.031045,-0.033025

In [2]:
# Load in the Ratios
ratios = pd.read_csv('Data/Ratios.csv', sep=',', header=0)

ratios = ratios.drop(['sale_nwc', 'adate', 'qdate'], 1)

ratios.columns.values[1] = 'date'
ratios['date'] = ratios.date.str[3:]

display(ratios.head())

,permno,date,CAPEI,bm,evm,pe_op_basic,pe_op_dil,pe_exi,pe_inc,ps,...,sale_equity,rd_sale,adv_sale,staff_sale,accrual,ptb,PEG_trailing,divyield,PEG_1yrforward,PEG_ltgforward
0,10107,01/2006,33.861,0.176,15.245,23.074,23.264,23.856,23.856,7.211,...,0.845,0.151,0.025,0.0,0.055,6.019,11.538,1.14%,15.506,2.109
1,10107,02/2006,31.756,0.163,14.951,21.496,21.846,22.392,22.392,6.713,...,0.880,0.151,0.025,0.0,0.036,6.281,10.280,1.34%,14.555,1.838
2,10107,03/2006,31.820,0.163,14.951,21.768,22.122,22.675,22.675,6.727,...,0.880,0.151,0.025,0.0,0.036,6.293,10.410,1.32%,14.739,1.842
3,10107,04/2006,28.176,0.163,14.951,19.320,19.634,20.125,20.125,5.957,...,0.880,0.151,0.025,0.0,0.036,5.573,9.239,1.49%,13.081,1.666
4,10107,05/2006,25.921,0.151,15.120,17.695,17.835,17.976,17.976,5.419,...,0.934,0.150,0.025,0.0,0.024,5.496,0.709,1.59%,-5.842,1.480

In [3]:
# Merging the two dataframes
data = pd.merge(df, ratios, left_on=['date', 'permno'], right_on=['date', 'permno'])
display(data.head())

,permno,date,SICCD,TICKER,COMNAM,BIDLO,ASKHI,PRC,BID,ASK,...,sale_equity,rd_sale,adv_sale,staff_sale,accrual,ptb,PEG_trailing,divyield,PEG_1yrforward,PEG_ltgforward
0,10107,01/2006,7370.0,MSFT,MICROSOFT CORP,26.28,28.15,28.15,28.15,28.13,...,0.845,0.151,0.025,0.0,0.055,6.019,11.538,1.14%,15.506,2.109
1,10107,02/2006,7370.0,MSFT,MICROSOFT CORP,26.39,28.04,26.87,26.87,26.88,...,0.880,0.151,0.025,0.0,0.036,6.281,10.280,1.34%,14.555,1.838
2,10107,03/2006,7370.0,MSFT,MICROSOFT CORP,26.85,27.89,27.21,27.24,27.24,...,0.880,0.151,0.025,0.0,0.036,6.293,10.410,1.32%,14.739,1.842
3,10107,04/2006,7370.0,MSFT,MICROSOFT CORP,24.15,27.74,24.15,24.16,24.16,...,0.880,0.151,0.025,0.0,0.036,5.573,9.239,1.49%,13.081,1.666
4,10107,05/2006,7370.0,MSFT,MICROSOFT CORP,22.56,24.29,22.65,22.70,22.70,...,0.934,0.150,0.025,0.0,0.024,5.496,0.709,1.59%,-5.842,1.480

permno               0
date                 0
SICCD                0
TICKER               0
COMNAM               0
BIDLO                0
ASKHI                0
PRC                  0
BID                  0
ASK                  0
vwretd               0
vwretx               0
CAPEI                9
bm                   9
evm                  1
pe_op_basic          2
pe_op_dil            2
pe_exi               2
pe_inc               2
ps                   1
pcf                  4
dpr                  7
npm                  1
opmbd                1
opmad                1
gpm                  1
ptpm                 1
cfm                  1
roa                  4
roe                 13
                  ...
profit_lct         600
ocf_lct            600
cash_debt           13
fcf_ocf            102
lt_ppent           121
dltt_be             11
debt_assets          1
debt_capital         1
de_ratio             1
intcov             286
intcov_ratio       286
cash_ratio         600
quick_ratio        600
curr_ratio         600
cash_conversion    589
inv_turn           406
at_turn              4
rect_turn            4
pay_turn             4
sale_invcap          1
sale_equity          7
rd_sale              1
adv_sale             1
staff_sale           1
accrual              4
ptb                  9
PEG_trailing       770
divyield           145
PEG_1yrforward      67
PEG_ltgforward      37
Length: 82, dtype: int64